GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
   "name": "Ada Lovelace",
   "number": "39-445323523"
}

###
DELETE http://localhost:3001/api/persons/63224025aa0129d4a7167411